version: '2'
services:

  beamium:
    build: 
      context: ./beamium    
      args:
      - hostname=YOUR_HOST
      # With /api/v0/update
      - warp10_endpoint=YOUR_ENDPOINT
      - warp10_token=YOUR_TOKEN
    links:
    - noderig:noderig
    depends_on:
    - noderig
  
  noderig:
    build: ./noderig
    ports:
     - "9100:9100"
